name: The ordinary madness of computer science
description: >- # this means to ignore newlines until "baseurl:"
  As I found out that github offers the possibility to publish small websites and blogs
  I decided to publish some of the random stuff I come accross
meta_description: "The ordinary madness of computer science"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
# baseurl: use '' for default
baseurl: ""
domain_name: ""
google_analytics: 'UA-112478462-1'
plugins:
 - jekyll-paginate
 - jemoji

# Details for the RSS feed generator
url:            'https://whymatter.github.io'
author:         'Oliver Seitz'
