name: The ordinary madness of computer science
description: >- # this means to ignore newlines until "baseurl:"
  Interesting things about programming, neural networks, computer vision
meta_description: "The ordinary madness of computer science"
about: '/about'

markdown: kramdown
highlighter: rouge
paginate: 15
# baseurl: use '' for default
baseurl: ""
domain_name: ""
google_analytics: 'UA-112478462-1'
plugins:
 - jekyll-paginate
 - jemoji
 - jekyll-seo-tag
 - jekyll-sitemap

# Details for the RSS feed generator
url:            'https://whymatter.github.io'
author:         'Oliver Seitz'
permalink:      '/posts/:title.html'
logo:           '/assets/images/profile.png'